export const sampleProducts = [
  // ================= MEN WEAR =================
  {
    name: "Classic Formal Suit",
    description: "Black slim-fit formal suit, perfect for weddings and parties.",
    price: 250, // per day rent
    offerPrice: 199,
    image: "https://images.unsplash.com/photo-1542062703-2fa1f3fe1cd6",
    category: "Men Wear",
    sizes: ["SM", "M", "L", "XL"],
    inStock: true,
  },
  {
    name: "Casual Denim Jacket",
    description: "Blue denim jacket for a stylish casual look.",
    price: 150,
    offerPrice: 120,
    image: "https://images.unsplash.com/photo-1539533113208-f6df8cc8b543",
    category: "Men Wear",
    sizes: ["M", "L", "XL"],
    inStock: true,
  },
  {
    name: "Traditional Kurta Set",
    description: "White cotton kurta with pajama, ideal for festivals.",
    price: 120,
    offerPrice: 95,
    image: "https://images.unsplash.com/photo-1621784563330-d0729d68a72e",
    category: "Men Wear",
    sizes: ["SM", "M", "L", "XL", "XXL"],
    inStock: true,
  },
  {
    name: "Party Wear Blazer",
    description: "Navy blue premium party wear blazer.",
    price: 300,
    offerPrice: 250,
    image: "https://images.unsplash.com/photo-1582312301031-1f6a1e76c2e7",
    category: "Men Wear",
    sizes: ["M", "L", "XL"],
    inStock: true,
  },
  {
    name: "Casual T-Shirt",
    description: "Round neck cotton t-shirt for everyday wear.",
    price: 60,
    offerPrice: 45,
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c",
    category: "Men Wear",
    sizes: ["SM", "M", "L", "XL", "XXL"],
    inStock: true,
  },

  // ================= WOMEN WEAR =================
  {
    name: "Evening Gown",
    description: "Elegant long gown with shimmer details for parties.",
    price: 350,
    offerPrice: 300,
    image: "https://images.unsplash.com/photo-1603252109303-2751441dd157",
    category: "Women Wear",
    sizes: ["SM", "M", "L", "XL"],
    inStock: true,
  },
  {
    name: "Silk Saree",
    description: "Traditional red silk saree with golden border.",
    price: 400,
    offerPrice: 320,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3",
    category: "Women Wear",
    sizes: ["M", "L", "XL"],
    inStock: true,
  },
  {
    name: "Western Dress",
    description: "Trendy floral print western dress.",
    price: 180,
    offerPrice: 140,
    image: "https://images.unsplash.com/photo-1519741497674-611481863552",
    category: "Women Wear",
    sizes: ["SM", "M", "L", "XL"],
    inStock: true,
  },
  {
    name: "Designer Lehenga",
    description: "Beautiful embroidered lehenga choli for weddings.",
    price: 600,
    offerPrice: 500,
    image: "https://images.unsplash.com/photo-1593032465171-8dff92e17bdb",
    category: "Women Wear",
    sizes: ["M", "L", "XL"],
    inStock: true,
  },
  {
    name: "Casual Kurti",
    description: "Comfortable cotton kurti for daily wear.",
    price: 90,
    offerPrice: 70,
    image: "https://images.unsplash.com/photo-1610030469983-689249475ed7",
    category: "Women Wear",
    sizes: ["SM", "M", "L", "XL", "XXL"],
    inStock: true,
  },

  // ================= KIDS WEAR =================
  {
    name: "Boys Party Suit",
    description: "3-piece kids suit for parties and weddings.",
    price: 180,
    offerPrice: 150,
    image: "https://images.unsplash.com/photo-1601049541161-7a4b7d317e9d",
    category: "Kids Wear",
    sizes: ["SM", "M", "L"],
    inStock: true,
  },
  {
    name: "Girls Frock Dress",
    description: "Cute floral frock for girls aged 3-8.",
    price: 120,
    offerPrice: 95,
    image: "https://images.unsplash.com/photo-1607746882042-944635dfe10e",
    category: "Kids Wear",
    sizes: ["SM", "M", "L"],
    inStock: true,
  },
  {
    name: "Ethnic Kurta for Boys",
    description: "Traditional kurta with pajama for kids.",
    price: 100,
    offerPrice: 80,
    image: "https://images.unsplash.com/photo-1617039483185-59f82bc5eacb",
    category: "Kids Wear",
    sizes: ["SM", "M", "L"],
    inStock: true,
  },
  {
    name: "Girls Lehenga Choli",
    description: "Beautiful kids lehenga set for special occasions.",
    price: 150,
    offerPrice: 120,
    image: "https://images.unsplash.com/photo-1621784562180-91e5c6f1a151",
    category: "Kids Wear",
    sizes: ["SM", "M", "L"],
    inStock: true,
  },
  {
    name: "Cartoon Print T-Shirt",
    description: "Soft cotton T-shirt with cartoon print.",
    price: 50,
    offerPrice: 35,
    image: "https://images.unsplash.com/photo-1627208112354-b90c06f7b2f0",
    category: "Kids Wear",
    sizes: ["SM", "M", "L"],
    inStock: true,
  },

  // ================= OCCASIONS =================
  {
    name: "Wedding Sherwani",
    description: "Royal sherwani with embroidery, perfect for weddings.",
    price: 700,
    offerPrice: 600,
    image: "https://images.unsplash.com/photo-1621784562180-91e5c6f1a151",
    category: "Occasions or Themes",
    sizes: ["M", "L", "XL", "XXL"],
    inStock: true,
  },
  {
    name: "Reception Gown",
    description: "Stylish gown for receptions & evening events.",
    price: 500,
    offerPrice: 420,
    image: "https://images.unsplash.com/photo-1603252109303-2751441dd157",
    category: "Occasions or Themes",
    sizes: ["SM", "M", "L", "XL"],
    inStock: true,
  },
  {
    name: "Birthday Dress",
    description: "Cute dress designed for birthday celebrations.",
    price: 200,
    offerPrice: 160,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3",
    category: "Occasions or Themes",
    sizes: ["SM", "M", "L"],
    inStock: true,
  },
  {
    name: "Festival Kurta Set",
    description: "Traditional wear for Diwali, Eid, and other festivals.",
    price: 250,
    offerPrice: 200,
    image: "https://images.unsplash.com/photo-1621784563330-d0729d68a72e",
    category: "Occasions or Themes",
    sizes: ["M", "L", "XL"],
    inStock: true,
  },
  {
    name: "Theme Party Costume",
    description: "Superhero themed costume for parties.",
    price: 150,
    offerPrice: 120,
    image: "https://images.unsplash.com/photo-1601049541161-7a4b7d317e9d",
    category: "Occasions or Themes",
    sizes: ["SM", "M", "L"],
    inStock: true,
  },

  // ================= SEASONAL =================
  {
    name: "Winter Jacket",
    description: "Warm padded jacket for cold winters.",
    price: 250,
    offerPrice: 200,
    image: "https://images.unsplash.com/photo-1602810318383-e7f63fddc5f6",
    category: "Seasonal",
    sizes: ["M", "L", "XL"],
    inStock: true,
  },
  {
    name: "Summer Cotton Kurta",
    description: "Lightweight cotton kurta for summer comfort.",
    price: 120,
    offerPrice: 95,
    image: "https://images.unsplash.com/photo-1621784563330-d0729d68a72e",
    category: "Seasonal",
    sizes: ["SM", "M", "L", "XL"],
    inStock: true,
  },
  {
    name: "Raincoat Set",
    description: "Waterproof raincoat with hood for rainy season.",
    price: 100,
    offerPrice: 80,
    image: "https://images.unsplash.com/photo-1627208112354-b90c06f7b2f0",
    category: "Seasonal",
    sizes: ["SM", "M", "L", "XL"],
    inStock: true,
  },
  {
    name: "Woolen Sweater",
    description: "Soft woolen sweater for chilly evenings.",
    price: 150,
    offerPrice: 120,
    image: "https://images.unsplash.com/photo-1602810318383-e7f63fddc5f6",
    category: "Seasonal",
    sizes: ["M", "L", "XL"],
    inStock: true,
  },
  {
    name: "Beach Wear Set",
    description: "Cool and trendy beach wear for summer vacations.",
    price: 180,
    offerPrice: 150,
    image: "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb",
    category: "Seasonal",
    sizes: ["SM", "M", "L", "XL"],
    inStock: true,
  },
];
